# Generated by Django 4.2.11 on 2024-05-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=360)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('quentity', models.IntegerField(default=1)),
                ('regular_price', models.IntegerField(default=1)),
                ('discount_price', models.IntegerField(default=0)),
                ('Product_image', models.ImageField(upload_to='product')),
                ('product_more_image1', models.ImageField(blank=True, null=True, upload_to='more image')),
                ('product_more_image2', models.ImageField(blank=True, null=True, upload_to='more image')),
                ('product_more_image3', models.ImageField(blank=True, null=True, upload_to='more image')),
                ('product_more_image4', models.ImageField(blank=True, null=True, upload_to='more image')),
                ('video_id', models.URLField(blank=True, max_length=600, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('product_details', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='more image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quentity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('delivery_charge', models.IntegerField(default=0)),
                ('customar_name', models.CharField(max_length=260)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('location_area', models.CharField(max_length=200)),
                ('is_deliverd', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
            ],
        ),
    ]
