# Generated by Django 4.2.11 on 2024-05-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customar_name', models.CharField(max_length=260)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('location_area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=360)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('quentity', models.IntegerField(default=1)),
                ('regular_price', models.IntegerField(default=1)),
                ('discount_price', models.IntegerField(default=0)),
                ('Product_image', models.ImageField(upload_to='product')),
                ('video_thumbnel', models.ImageField(blank=True, null=True, upload_to='thumbnel')),
                ('video_id', models.CharField(blank=True, max_length=260, null=True)),
                ('product_details', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
